<a href="https://colab.research.google.com/github/monahusein/Hw/blob/main/Task_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

import numpy as np
def describe(ar):
    """Print out a summary of an array."""
    print(f'dimensions: {ar.ndim}')
    print(f'shape: {ar.shape}')
    print(f'size: {ar.size}')
    print(f'dtype: {ar.dtype}')
arr = np.array((1, 2, 3, 4))
describe(arr)

print("*"*50)

list1 = [1, 2, 3]
list2 = [4, 5, 6]
arr2 = np.array([list1, list2])
print(arr2)
print("*"*50)
describe(arr2)

print("*"*50)

arr2 = np.array([list1, list2], dtype =np.float64)
describe(arr2)
print("*"*50)
arr3 = np.ones((2, 2))
print(arr3)
print("*"*50)

arr4 = np.zeros((4, 3))
print(arr4)

print("*"*50)


arr5 = np.arange(10)
print(arr5)
print("*"*50)
arr6 = np.linspace(0, 30, 31)
print(arr6)
print("*"*50)
arr7 = np.linspace(0, 30, 10)
print(arr7)
print("*"*50)
arr8 = np.random.rand(2, 3)
print(8)
print("*"*50)

arr9 = np.random.randint
print(9)
print("*"*50)
arr10 = np.random.randn(5,5 )
print(arr10)
print("*"*50)
arr11 = arr4.reshape(12)
print(arr11)

print("*"*50)

arr12 = np.ones_like(arr11)
print(arr12)

print("*"*50)
arr13 = np.full(shape=(2, 2, 6), fill_value=8)
print(arr13)
print("*"*50)
arr14 = np.eye(N=5)
print(arr14)
print("*"*50)
describe(arr4)

dimensions: 1
shape: (4,)
size: 4
dtype: int64
**************************************************
[[1 2 3]
 [4 5 6]]
**************************************************
dimensions: 2
shape: (2, 3)
size: 6
dtype: int64
**************************************************
dimensions: 2
shape: (2, 3)
size: 6
dtype: float64
**************************************************
[[1. 1.]
 [1. 1.]]
**************************************************
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
**************************************************
[0 1 2 3 4 5 6 7 8 9]
**************************************************
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30.]
**************************************************
[ 0.          3.33333333  6.66666667 10.         13.33333333 16.66666667
 20.         23.33333333 26.66666667 30.        ]
**************************************************
8
*********************************